openapi: 3.0.3
info:
  title: Penguin Folder Management API
  description: API for managing and browsing folders with time parsing utilities
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local development server
paths:
  /folders:
    get:
      summary: Get folders
      description: Retrieve a list of folders from the specified path
      operationId: getFolders
      parameters:
        - name: path
          in: query
          description: Path to the directory to list
          required: false
          schema:
            type: string
            default: "~/penguin"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FolderListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /kouji-projects:
    get:
      summary: Get construction projects
      description: Retrieve a list of construction project folders from the specified path
      operationId: getKoujiProjects
      parameters:
        - name: path
          in: query
          description: Path to the directory containing construction projects
          required: false
          schema:
            type: string
            default: "~/penguin/豊田築炉/2-工事"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KoujiListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /kouji-projects/save:
    post:
      summary: Save construction project
      description: Save construction project information to YAML file
      operationId: saveKoujiProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KoujiSaveRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KoujiSaveResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /time/parse:
    post:
      summary: Parse time string
      description: Parse various date/time string formats
      operationId: parseTime
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeParseRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeParseResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /time/formats:
    get:
      summary: Get supported time formats
      description: Get list of all supported date/time formats
      operationId: getSupportedFormats
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportedFormatsResponse'
components:
  schemas:
    Folder:
      type: object
      required:
        - id
        - name
        - path
        - is_directory
        - size
        - modified_time
      properties:
        id:
          type: integer
          format: uint64
          description: Unique identifier for the folder
          example: 123456
        name:
          type: string
          description: Name of the file or folder
          example: "documents"
        path:
          type: string
          description: Full path to the file or folder
          example: "/home/user/documents"
        is_directory:
          type: boolean
          description: Whether this item is a directory
          example: true
        size:
          type: integer
          format: int64
          description: Size of the file in bytes
          example: 4096
        modified_time:
          type: string
          format: date-time
          description: Last modification time
          example: "2024-01-15T10:30:00Z"
    FolderListResponse:
      type: object
      required:
        - folders
        - count
      properties:
        folders:
          type: array
          items:
            $ref: '#/components/schemas/Folder'
        count:
          type: integer
          description: Total number of folders returned
          example: 10
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type
          example: "Failed to read directory"
        message:
          type: string
          description: Detailed error message
          example: "Permission denied"
    TimeParseRequest:
      type: object
      required:
        - time_string
      properties:
        time_string:
          type: string
          description: Time string to parse
          example: "2024-01-15T10:30:00"
    TimeParseResponse:
      type: object
      required:
        - original
        - rfc3339
        - unix
        - readable
        - timezone
      properties:
        original:
          type: string
          description: Original input string
          example: "2024-01-15T10:30:00"
        rfc3339:
          type: string
          description: Parsed time in RFC3339 format
          example: "2024-01-15T10:30:00Z"
        unix:
          type: integer
          format: int64
          description: Unix timestamp
          example: 1705318200
        readable:
          type: string
          description: Human readable format
          example: "January 15, 2024 10:30 AM"
        timezone:
          type: string
          description: Time zone used
          example: "Local"
    TimeFormat:
      type: object
      required:
        - name
        - pattern
        - example
      properties:
        name:
          type: string
          description: Format name
          example: "RFC3339"
        pattern:
          type: string
          description: Format pattern
          example: "2006-01-02T15:04:05Z07:00"
        example:
          type: string
          description: Example value
          example: "2024-01-15T10:30:00Z"
    SupportedFormatsResponse:
      type: object
      required:
        - formats
      properties:
        formats:
          type: array
          items:
            $ref: '#/components/schemas/TimeFormat'
    Kouji:
      type: object
      required:
        - id
        - company_name
        - location_name
        - status
        - start_date
        - end_date
        - description
        - tags
        - file_count
        - subdir_count
        - name
        - path
        - is_directory
        - size
        - modified_time
      properties:
        id:
          type: string
          description: Generated by Folder ID + CompanyName + LocationName
          example: "Generated by Folder ID + CompanyName + LocationName"
        company_name:
          type: string
          description: Construction company name
          example: "豊田築炉"
        location_name:
          type: string
          description: Construction site location name
          example: "名和工場"
        status:
          type: string
          description: Project status
          example: "進行中"
        start_date:
          type: string
          format: date-time
          description: Project start date
          example: "2024-01-01T00:00:00Z"
        end_date:
          type: string
          format: date-time
          description: Project end date
          example: "2024-12-31T00:00:00Z"
        description:
          type: string
          description: Project description
          example: "工事関連の資料とドキュメント"
        tags:
          type: array
          items:
            type: string
          description: Project tags
          example: ["工事", "豊田築炉", "名和工場"]
        file_count:
          type: integer
          description: Number of files in the project
          example: 42
        subdir_count:
          type: integer
          description: Number of subdirectories in the project
          example: 5
        # Embedded Folder properties
        name:
          type: string
          description: Name of the project folder
          example: "2025-0114 豊田築炉 名和工場"
        path:
          type: string
          description: Full path to the project folder
          example: "/home/user/projects/2025-0114 豊田築炉 名和工場"
        is_directory:
          type: boolean
          description: Whether this item is a directory (always true for projects)
          example: true
        size:
          type: integer
          format: int64
          description: Total size of all files in bytes
          example: 1073741824
        modified_time:
          type: string
          format: date-time
          description: Last modification time
          example: "2024-01-15T10:30:00Z"
    KoujiListResponse:
      type: object
      required:
        - kouji_list
        - count
      properties:
        kouji_list:
          type: array
          items:
            $ref: '#/components/schemas/Kouji'
          description: List of kouji projects
        count:
          type: integer
          description: Total number of projects returned
          example: 10
        total_size:
          type: integer
          format: int64
          description: Total size of all files in bytes
          example: 1073741824
    KoujiSaveRequest:
      type: object
      required:
        - project_path
        - project_data
      properties:
        project_path:
          type: string
          description: Path to the project folder
          example: "/home/user/projects/2025-0114 豊田築炉 名和工場"
        project_data:
          $ref: '#/components/schemas/Kouji'
    KoujiSaveResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          description: Whether the save operation was successful
          example: true
        message:
          type: string
          description: Success or error message
          example: "Project saved successfully"
        saved_path:
          type: string
          description: Path where the project was saved
          example: "/home/user/projects/2025-0114 豊田築炉 名和工場/.inside.yaml"