package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	messageStartRE     = regexp.MustCompile(`\bmessage\s+([A-Za-z0-9_]+)\s*\{`)
	tableNameCommentRE = regexp.MustCompile(`//\s*@manifest\s+table\s+name:\s*([A-Za-z0-9_]+)`)
	packageNameRE      = regexp.MustCompile(`^package\s+([A-Za-z0-9_.]+)\s*;`)
	fieldNameRE        = regexp.MustCompile(`^\s*((?:repeated\s+)?[\w.<>,]+)\s+([A-Za-z0-9_]+)\s*=`)
)

// FieldInfo はフィールドの情報を保持します
type FieldInfo struct {
	Name string
	Type string
}

// MessageBlock はメッセージブロックの解析状態を保持します
type MessageBlock struct {
	Name         string
	BraceBalance int
	Fields       []FieldInfo
	TableName    string
}

// UpdateBalance は括弧のバランスを更新します
func (m *MessageBlock) UpdateBalance(line string) {
	m.BraceBalance += strings.Count(line, "{")
	m.BraceBalance -= strings.Count(line, "}")
}

// IsClosed はメッセージブロックが閉じられたかを判定します
func (m *MessageBlock) IsClosed() bool {
	return m.BraceBalance <= 0
}

// extractPackageName は proto ファイルから package 名を抽出します
func extractPackageName(lines []string) string {
	for _, line := range lines {
		match := packageNameRE.FindStringSubmatch(strings.TrimSpace(line))
		if match != nil {
			// ドットを削除して migration を追加
			pkg := strings.ReplaceAll(match[1], ".", "")
			return pkg + "migration"
		}
	}
	return "migration"
}

// protoTypeToSQL は proto の型を SQL の型に変換します
func protoTypeToSQL(protoType string) string {
	protoType = strings.TrimSpace(protoType)
	if strings.HasPrefix(protoType, "repeated ") {
		protoType = strings.TrimSpace(protoType[9:])
	}

	typeMap := map[string]string{
		"string":                    "TEXT",
		"int32":                     "INTEGER",
		"int64":                     "INTEGER",
		"uint32":                    "INTEGER",
		"uint64":                    "INTEGER",
		"bool":                      "INTEGER",
		"float":                     "REAL",
		"double":                    "REAL",
		"google.protobuf.Timestamp": "TEXT", // RFC3339Nano (ISO8601拡張形式)
	}

	if sqlType, ok := typeMap[protoType]; ok {
		return sqlType
	}
	return "TEXT"
}

// generateCreateTableSQL はメッセージ情報から CREATE TABLE SQL を生成します
func generateCreateTableSQL(messageName, tableName string, fields []FieldInfo) string {
	if tableName == "" {
		tableName = strings.ToLower(messageName) + "s"
	}

	var lines []string
	lines = append(lines, fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (", tableName))
	lines = append(lines, "    id TEXT PRIMARY KEY,")

	for _, field := range fields {
		sqlType := protoTypeToSQL(field.Type)
		lines = append(lines, fmt.Sprintf("    %s %s NOT NULL,", field.Name, sqlType))
	}

	// 最後のカンマを削除して閉じる
	lastIdx := len(lines) - 1
	lines[lastIdx] = strings.TrimSuffix(lines[lastIdx], ",")
	lines = append(lines, ");")

	return strings.Join(lines, "\n")
}

// generateGoFile はマッチしたメッセージから Go ファイルを生成します
func generateGoFile(matches []MessageMatch, packageName string) string {
	var lines []string
	lines = append(lines, "// Code generated by cmd/migrate. DO NOT EDIT.")
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("package %s", packageName))
	lines = append(lines, "")
	lines = append(lines, "// DefaultMigrations returns SQL migration statements for manifest tables.")
	lines = append(lines, "func DefaultMigrations() []string {")
	lines = append(lines, "\treturn []string{")

	for _, match := range matches {
		sql := generateCreateTableSQL(match.Name, match.TableName, match.Fields)
		lines = append(lines, fmt.Sprintf("\t\t// Message: %s", match.Name))
		if match.TableName != "" {
			lines = append(lines, fmt.Sprintf("\t\t// Table: %s", match.TableName))
		}

		// SQL をバッククォートで囲んでインデントする
		sqlLines := strings.Split(sql, "\n")
		lines = append(lines, "\t\t`"+sqlLines[0])
		for _, sqlLine := range sqlLines[1:] {
			lines = append(lines, "\t\t\t"+sqlLine)
		}
		lines = append(lines, "\t\t`,")
		lines = append(lines, "")
	}

	// 最後の空行を削除
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}

	lines = append(lines, "\t}")
	lines = append(lines, "}")
	lines = append(lines, "") // ファイル末尾に改行

	return strings.Join(lines, "\n")
}

// MessageMatch はマッチしたメッセージの情報を保持します
type MessageMatch struct {
	Name      string
	Fields    []FieldInfo
	TableName string
}

// parseMessages は proto ファイルから mf_ フィールドを含むメッセージを解析します
func parseMessages(lines []string) []MessageMatch {
	var stack []*MessageBlock
	var matches []MessageMatch
	pendingTableName := ""

	for _, line := range lines {
		// テーブル名のコメントをチェック
		if match := tableNameCommentRE.FindStringSubmatch(line); match != nil {
			pendingTableName = match[1]
		}

		// メッセージ開始をチェック
		if match := messageStartRE.FindStringSubmatch(line); match != nil {
			name := match[1]
			block := &MessageBlock{
				Name:         name,
				BraceBalance: 0,
				Fields:       []FieldInfo{},
				TableName:    pendingTableName,
			}
			block.UpdateBalance(line)
			stack = append(stack, block)
			pendingTableName = "" // リセット
			continue
		}

		if len(stack) == 0 {
			continue
		}

		// 現在のブロックに対してフィールドをチェック
		block := stack[len(stack)-1]
		if match := fieldNameRE.FindStringSubmatch(line); match != nil {
			fieldType := match[1]
			fieldName := match[2]
			if strings.HasPrefix(fieldName, "mf_") {
				block.Fields = append(block.Fields, FieldInfo{
					Name: fieldName,
					Type: fieldType,
				})
			}
		}

		block.UpdateBalance(line)
		if block.IsClosed() {
			finished := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			if len(finished.Fields) > 0 {
				matches = append(matches, MessageMatch{
					Name:      finished.Name,
					Fields:    finished.Fields,
					TableName: finished.TableName,
				})
			}
		}
	}

	return matches
}

func main() {
	protoPath := flag.String("proto", "../proto/grpc/v1/toyotachikuro.proto", "解析する proto ファイルのパス")
	outputPath := flag.String("output", "", "Go ファイルの出力先パス (指定しない場合は標準出力)")
	flag.Parse()

	// proto ファイルの存在確認
	if _, err := os.Stat(*protoPath); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "proto file not found: %s\n", *protoPath)
		os.Exit(1)
	}

	// proto ファイルの読み込み
	file, err := os.Open(*protoPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to open proto file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	var lines []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "failed to read proto file: %v\n", err)
		os.Exit(1)
	}

	// 解析処理
	packageName := extractPackageName(lines)
	matches := parseMessages(lines)

	if len(matches) == 0 {
		fmt.Println("manifest_ フィールドを持つメッセージは見つかりませんでした。")
		return
	}

	if *outputPath != "" {
		// Go ファイルとして出力
		goContent := generateGoFile(matches, packageName)
		outPath := *outputPath

		// 出力パスがディレクトリの場合、proto ファイル名を使用
		info, err := os.Stat(outPath)
		if err == nil && info.IsDir() {
			baseName := strings.TrimSuffix(filepath.Base(*protoPath), ".proto")
			outPath = filepath.Join(outPath, baseName+".go")
		} else if !strings.HasSuffix(outPath, ".go") {
			baseName := strings.TrimSuffix(filepath.Base(*protoPath), ".proto")
			outPath = filepath.Join(outPath, baseName+".go")
		}

		// 出力ディレクトリを作成
		if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "failed to create output directory: %v\n", err)
			os.Exit(1)
		}

		// ファイルに書き込み
		if err := os.WriteFile(outPath, []byte(goContent), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write output file: %v\n", err)
			os.Exit(1)
		}

		fmt.Printf("%d 件のメッセージから %s を生成しました。\n", len(matches), outPath)
		fmt.Printf("Package: %s\n", packageName)
	} else {
		// 標準出力に表示
		fmt.Printf("%s で manifest_ フィールドを含むメッセージ: %d 件\n\n", *protoPath, len(matches))

		for _, match := range matches {
			sql := generateCreateTableSQL(match.Name, match.TableName, match.Fields)
			fmt.Printf("// Message: %s\n", match.Name)
			if match.TableName != "" {
				fmt.Printf("// Table: %s\n", match.TableName)
			}
			fmt.Printf("`%s`,\n\n", sql)
		}
	}
}
