#!/usr/bin/env python3
"""
proto ファイルからフィールド名に ``persist_`` という接頭語を含むメッセージを抽出します。

単純な構文解析（正規表現＋波括弧カウンタ）でメッセージ定義を追跡しているため、
高度な proto 構文には対応しませんが、当リポジトリの定義には十分です。
"""

from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass, field
from typing import Iterable, List


MESSAGE_START = re.compile(r"\bmessage\s+([A-Za-z0-9_]+)\s*\{")
TABLE_NAME_COMMENT = re.compile(r"//\s*@persist\s+table\s+name:\s*([A-Za-z0-9_]+)")
PACKAGE_NAME = re.compile(r"^package\s+([A-Za-z0-9_.]+)\s*;")
FIELD_NAME = re.compile(
    r"""
    ^\s*                               # optional indent
    ((?:repeated\s+)?[\w.<>,]+)        # capture type (with optional repeated)
    \s+([A-Za-z0-9_]+)\s*=             # capture field name
    """,
    re.VERBOSE,
)

@dataclass
class FieldInfo:
    name: str
    type: str

@dataclass
class MessageBlock:
    name: str
    brace_balance: int
    fields: List[FieldInfo] = field(default_factory=list)
    table_name: str = ""

    def update_balance(self, line: str) -> None:
        self.brace_balance += line.count("{")
        self.brace_balance -= line.count("}")

    def is_closed(self) -> bool:
        return self.brace_balance <= 0


def extract_package_name(lines: Iterable[str]) -> str:
    """ proto ファイルから package 名を抽出します。"""
    for line in lines:
        match = PACKAGE_NAME.match(line.strip())
        if match:
            # ドットを削除してmigrationを追加
            package = match.group(1).replace(".", "")
            return f"{package}migration"
    return "migration"


def proto_type_to_sql(proto_type: str) -> str:
    """proto の型を SQL の型に変換します。"""
    proto_type = proto_type.strip()
    if proto_type.startswith("repeated "):
        proto_type = proto_type[9:].strip()
    
    type_map = {
        "string": "TEXT",
        "int32": "INTEGER",
        "int64": "INTEGER",
        "uint32": "INTEGER",
        "uint64": "INTEGER",
        "bool": "INTEGER",
        "float": "REAL",
        "double": "REAL",
        # TEXT形式でRFC3339Nano (ISO8601拡張形式) を使用
        # 例: 2026-01-03T15:30:45.123456789+09:00
        # ナノ秒精度とタイムゾーンオフセットを保持
        "google.protobuf.Timestamp": "TEXT",
    }
    
    return type_map.get(proto_type, "TEXT")


def generate_create_table_sql(message_name: str, table_name: str, fields: List[FieldInfo]) -> str:
    """メッセージ情報から CREATE TABLE SQL を生成します。"""
    if not table_name:
        table_name = message_name.lower() + "s"
    
    sql_lines = [f"CREATE TABLE IF NOT EXISTS {table_name} ("]
    sql_lines.append("    id TEXT PRIMARY KEY,")
    
    for field in fields:
        sql_type = proto_type_to_sql(field.type)
        sql_lines.append(f"    {field.name} {sql_type} NOT NULL,")
    
    # 最後のカンマを削除して閉じる
    sql_lines[-1] = sql_lines[-1].rstrip(",")
    sql_lines.append(");")
    
    return "\n".join(sql_lines)


def generate_go_file(matches: List[tuple[str, List[FieldInfo], str]], package_name: str) -> str:
    """マッチしたメッセージから Go ファイルを生成します。"""
    lines = [
        "// Code generated by migrate_persist_messages.py. DO NOT EDIT.",
        "",
        f"package {package_name}",
        "",
        "// DefaultMigrations returns SQL migration statements for persist tables.",
        "func DefaultMigrations() []string {",
        "\treturn []string{",
    ]
    
    for name, fields, table_name in matches:
        sql = generate_create_table_sql(name, table_name, fields)
        lines.append(f"\t\t// Message: {name}")
        if table_name:
            lines.append(f"\t\t// Table: {table_name}")
        
        # SQL をバッククォートで囲んでインデントする
        sql_lines = sql.split("\n")
        lines.append("\t\t`" + sql_lines[0])
        for sql_line in sql_lines[1:]:
            lines.append("\t\t\t" + sql_line)
        lines.append("\t\t`,")
        lines.append("")
    
    # 最後の空行を削除
    if lines[-1] == "":
        lines.pop()
    
    lines.append("\t}")
    lines.append("}")
    lines.append("")  # ファイル末尾に改行
    
    return "\n".join(lines)


def parse_messages(lines: Iterable[str]) -> List[tuple[str, List[FieldInfo], str]]:
    stack: List[MessageBlock] = []
    matches: List[tuple[str, List[FieldInfo], str]] = []
    pending_table_name: str = ""

    for line in lines:
        # Check for table name comment
        table_name_match = TABLE_NAME_COMMENT.search(line)
        if table_name_match:
            pending_table_name = table_name_match.group(1)
        
        start_match = MESSAGE_START.search(line)
        if start_match:
            name = start_match.group(1)
            block = MessageBlock(name=name, brace_balance=0, table_name=pending_table_name)
            block.update_balance(line)
            stack.append(block)
            pending_table_name = ""  # Reset after assignment
            continue

        if not stack:
            continue

        block = stack[-1]
        field_match = FIELD_NAME.match(line)
        if field_match:
            field_type = field_match.group(1)
            field_name = field_match.group(2)
            if field_name.startswith("persist_"):
                block.fields.append(FieldInfo(name=field_name, type=field_type))

        block.update_balance(line)
        if block.is_closed():
            finished = stack.pop()
            if finished.fields:
                matches.append((finished.name, finished.fields, finished.table_name))

    return matches


def main() -> None:
    
    # コマンドライン引数の解析
    parser = argparse.ArgumentParser(
        description="proto から persist_ フィールドを含むメッセージを抽出します。",
    )
    parser.add_argument(
        "--proto",
        default="proto/grpc/v1/toyotachikuro.proto",
        help="解析する proto ファイルのパス",
    )
    parser.add_argument(
        "--output",
        "-o",
        default="",
        help="Go ファイルの出力先パス (指定しない場合は標準出力)",
    )
    args = parser.parse_args()

    proto_path = pathlib.Path(args.proto)
    if not proto_path.exists():
        raise SystemExit(f"proto file not found: {proto_path}")

    # proto ファイルの読み込みと解析
    lines = proto_path.read_text(encoding="utf-8").splitlines()
    package_name = extract_package_name(lines)
    matches = parse_messages(lines)

    if not matches:
        print("persist_ フィールドを持つメッセージは見つかりませんでした。")
        return

    if args.output:
        # Go ファイルとして出力
        go_content = generate_go_file(matches, package_name)
        output_path = pathlib.Path(args.output)
        
        # 出力パスがディレクトリの場合、protoファイル名を使用
        if output_path.is_dir() or not output_path.suffix:
            base_name = proto_path.stem  # .proto を除いた名前
            output_path = output_path / f"{base_name}.go"
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(go_content, encoding="utf-8")
        print(f"{len(matches)} 件のメッセージから {output_path} を生成しました。")
        print(f"Package: {package_name}")
    else:
        # 標準出力に表示
        print(f"{proto_path} で persist_ フィールドを含むメッセージ: {len(matches)} 件\n")
        
        for name, fields, table_name in matches:
            sql = generate_create_table_sql(name, table_name, fields)
            print(f"// Message: {name}")
            if table_name:
                print(f"// Table: {table_name}")
            print(f"`{sql}`,\n")


if __name__ == "__main__":
    main()
